[package]
name = "rust-simple-api"
version = "0.1.0"
authors = ["Jóni Oliveira <joni.oliveira89@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"